# Generated by Django 4.2.7 on 2025-12-29 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                (
                    "type_post",
                    models.CharField(
                        choices=[
                            ("annonce", "Annonce"),
                            ("info", "Information"),
                            ("actualite", "Actualité"),
                            ("alerte", "Alerte"),
                            ("evenement", "Événement"),
                        ],
                        default="annonce",
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="posts/")),
                (
                    "publique",
                    models.BooleanField(
                        default=True, help_text="Visible par tous les utilisateurs"
                    ),
                ),
                (
                    "prioritaire",
                    models.BooleanField(
                        default=False, help_text="Afficher en haut de la liste"
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date après laquelle le post ne sera plus affiché",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-prioritaire", "-date_publication"],
            },
        ),
    ]
