# Generated by Django 4.2.7 on 2025-12-29 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("examen", "Examen"),
                            ("vacances", "Vacances"),
                            ("fete", "Fête"),
                            ("reunion", "Réunion"),
                            ("activite", "Activité"),
                            ("rappel", "Rappel"),
                        ],
                        default="rappel",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("heure_debut", models.TimeField(blank=True, null=True)),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                ("couleur", models.CharField(default="#007bff", max_length=20)),
                (
                    "rappel_jours",
                    models.IntegerField(
                        default=1, help_text="Nombre de jours avant pour le rappel"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Visible par tous les utilisateurs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.matiere",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements_personnels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_debut"],
                "indexes": [
                    models.Index(
                        fields=["date_debut"], name="calendar_ap_date_de_6638d8_idx"
                    ),
                    models.Index(
                        fields=["user", "date_debut"],
                        name="calendar_ap_user_id_4c42ef_idx",
                    ),
                ],
            },
        ),
    ]
