# Generated by Django 4.2.7 on 2025-12-29 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mot_francais", models.CharField(max_length=200)),
                ("mot_ewe", models.CharField(blank=True, max_length=200)),
                ("mot_kab", models.CharField(blank=True, max_length=200)),
                ("definition", models.TextField(blank=True)),
                ("categorie", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["mot_francais"],
            },
        ),
        migrations.CreateModel(
            name="Traduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte_original", models.TextField()),
                (
                    "langue_originale",
                    models.CharField(
                        choices=[("ewe", "Éwé"), ("kab", "Kabiyè"), ("fr", "Français")],
                        default="fr",
                        max_length=3,
                    ),
                ),
                (
                    "langue_cible",
                    models.CharField(
                        choices=[("ewe", "Éwé"), ("kab", "Kabiyè"), ("fr", "Français")],
                        max_length=3,
                    ),
                ),
                ("texte_traduit", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traductions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
