# Generated by Django 4.2.7 on 2025-12-29 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icone", models.CharField(default="🏆", max_length=50)),
                ("couleur", models.CharField(default="gold", max_length=20)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("qcm_first", "Premier QCM complété"),
                            ("qcm_perfect", "QCM parfait (100%)"),
                            ("qcm_10", "10 QCM complétés"),
                            ("qcm_50", "50 QCM complétés"),
                            ("flashcard_10", "10 Flashcards créées"),
                            ("flashcard_50", "50 Flashcards créées"),
                            ("flashcard_perfect", "Session flashcards parfaite"),
                            ("study_streak_3", "3 jours consécutifs"),
                            ("study_streak_7", "7 jours consécutifs"),
                            ("study_streak_30", "30 jours consécutifs"),
                            ("tutor_10", "10 questions au tuteur"),
                            ("profile_complete", "Profil complet"),
                            ("first_resume", "Premier résumé créé"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points_xp", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["points_xp"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_xp", models.IntegerField(default=0)),
                ("niveau", models.IntegerField(default=1)),
                ("jours_streak", models.IntegerField(default=0)),
                ("dernier_activite", models.DateField(blank=True, null=True)),
                ("qcm_completes", models.IntegerField(default=0)),
                ("flashcards_creees", models.IntegerField(default=0)),
                ("questions_tuteur", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obtenu_le", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisateurs",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges_obtenus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-obtenu_le"],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("all_time", "Tous les temps"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["periode", "position"],
                "unique_together": {("user", "periode", "date")},
            },
        ),
    ]
