# Generated by Django 4.2.7 on 2025-12-29 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                (
                    "type_filiere",
                    models.CharField(
                        choices=[
                            ("scientifique", "Scientifique"),
                            ("litteraire", "Littéraire"),
                            ("commercial", "Commercial"),
                            ("technique", "Technique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("matieres_principales", models.JSONField(default=list)),
                ("metiers", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reponses",
                    models.JSONField(
                        default=dict, help_text="Réponses au questionnaire"
                    ),
                ),
                ("score_scientifique", models.IntegerField(default=0)),
                ("score_litteraire", models.IntegerField(default=0)),
                ("score_commercial", models.IntegerField(default=0)),
                ("score_technique", models.IntegerField(default=0)),
                ("filiere_suggeree", models.CharField(blank=True, max_length=200)),
                ("metiers_suggestes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Metier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("competences", models.JSONField(default=list)),
                ("formation_requise", models.TextField(blank=True)),
                (
                    "filieres",
                    models.ManyToManyField(
                        related_name="metiers_liste", to="orientation.filiere"
                    ),
                ),
            ],
        ),
    ]
