# Generated by Django 4.2.7 on 2025-12-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionplanifiee",
            name="type_revision",
            field=models.CharField(
                choices=[
                    ("lecture", "Lecture"),
                    ("qcm", "QCM"),
                    ("flashcard", "Flashcards"),
                    ("exercices", "Exercices"),
                    ("resume", "Résumé"),
                ],
                default="lecture",
                max_length=50,
            ),
        ),
    ]
